// AUTO-GENERATED — do not edit manually
// Run: node scripts/generate_audio.js
export const audioMap = {
  "Hello Explorer! Today we'll unlock the secret of big numbers!": "/assets/audio/audio_hello_explorer_today_we_ll_unlock_the_se_0.mp3",
  "Get ready to discover thousands, hundreds, tens, and ones!": "/assets/audio/audio_get_ready_to_discover_thousands_hundreds_1.mp3",
  "Priya, Kai, and Liam were on a school trip to the Number Museum in Singapore. Look! gasped Priya, pointing at a giant glowing display. That number is three thousand, four hundred and seventy-two! It's huge, said Kai. But what does each part mean?": "/assets/audio/audio_priya_kai_and_liam_were_on_a_school_trip_16.mp3",
  "A friendly robot guide rolled up to them. Welcome, explorers! Every digit in a number lives in its own house. Four glowing houses appeared: Thousands, Hundreds, Tens, and Ones. The house a digit lives in tells you its value!": "/assets/audio/audio_a_friendly_robot_guide_rolled_up_to_them_17.mp3",
  "Let's break down three thousand four hundred and seventy-two, said the robot. The digit 3 lives in the Thousands house, so it's worth three thousand! That's like three thousand mangoes from a Mumbai market! laughed Priya. And the 4 in the Hundreds house is worth four hundred!": "/assets/audio/audio_let_s_break_down_three_thousand_four_hun_18.mp3",
  "The 7 in the Tens house is worth seventy, continued the robot. And the 2 in the Ones house is worth just two! So it all adds up! said Kai excitedly. Three thousand plus four hundred plus seventy plus two equals three thousand, four hundred and seventy-two! That's like counting cherry blossoms in Tokyo!": "/assets/audio/audio_the_7_in_the_tens_house_is_worth_seventy_19.mp3",
  "Wait, said Liam. My dad says our village in Nairobi has four thousand and eight people. What about the zeros? The robot smiled. Zero means nobody lives in that house. But the house must still exist, or all the other digits would get confused! So zero is a placeholder! said Liam. It holds the spot even if it's empty!": "/assets/audio/audio_wait_said_liam_my_dad_says_our_village_i_20.mp3",
  "I get it! shouted Kai. The Tokyo Skytree is six hundred and thirty-four metres tall. That's 6 hundreds, 3 tens, and 4 ones! And my school in Mumbai has two thousand, three hundred and fifty students, added Priya. That's 2 thousands, 3 hundreds, 5 tens, and 0 ones! The three friends cheered. They had cracked the code of big numbers!": "/assets/audio/audio_i_get_it_shouted_kai_the_tokyo_skytree_i_21.mp3",
  "Priya, Kai, and Liam were on a school trip to the Number Museum in Singapore.": "/assets/audio/audio_priya_kai_and_liam_were_on_a_school_trip_22.mp3",
  "Look! gasped Priya, pointing at a giant glowing display.": "/assets/audio/audio_look_gasped_priya_pointing_at_a_giant_gl_23.mp3",
  "That number is three thousand, four hundred and seventy-two!": "/assets/audio/audio_that_number_is_three_thousand_four_hundr_24.mp3",
  "It's huge, said Kai. But what does each part mean?": "/assets/audio/audio_it_s_huge_said_kai_but_what_does_each_pa_25.mp3",
  "A friendly robot guide rolled up to them.": "/assets/audio/audio_a_friendly_robot_guide_rolled_up_to_them_26.mp3",
  "Welcome, explorers! Every digit in a number lives in its own house.": "/assets/audio/audio_welcome_explorers_every_digit_in_a_numbe_27.mp3",
  "Four glowing houses appeared: Thousands, Hundreds, Tens, and Ones.": "/assets/audio/audio_four_glowing_houses_appeared_thousands_h_28.mp3",
  "The house a digit lives in tells you its value!": "/assets/audio/audio_the_house_a_digit_lives_in_tells_you_its_29.mp3",
  "Let's break down three thousand, four hundred and seventy-two, said the robot.": "/assets/audio/audio_let_s_break_down_three_thousand_four_hun_30.mp3",
  "The digit three lives in the Thousands house, so it's worth three thousand!": "/assets/audio/audio_the_digit_three_lives_in_the_thousands_h_31.mp3",
  "That's like three thousand mangoes from a Mumbai market! laughed Priya.": "/assets/audio/audio_that_s_like_three_thousand_mangoes_from__32.mp3",
  "And the four in the Hundreds house is worth four hundred!": "/assets/audio/audio_and_the_four_in_the_hundreds_house_is_wo_33.mp3",
  "The seven in the Tens house is worth seventy.": "/assets/audio/audio_the_seven_in_the_tens_house_is_worth_sev_34.mp3",
  "And the two in the Ones house is worth just two!": "/assets/audio/audio_and_the_two_in_the_ones_house_is_worth_j_35.mp3",
  "So it all adds up! said Kai excitedly.": "/assets/audio/audio_so_it_all_adds_up_said_kai_excitedly__36.mp3",
  "Three thousand plus four hundred plus seventy plus two equals three thousand, four hundred and seventy-two!": "/assets/audio/audio_three_thousand_plus_four_hundred_plus_se_37.mp3",
  "That's like counting cherry blossoms in Tokyo!": "/assets/audio/audio_that_s_like_counting_cherry_blossoms_in__38.mp3",
  "Wait, said Liam. My dad says our village in Nairobi has four thousand and eight people. What about the zeros?": "/assets/audio/audio_wait_said_liam_my_dad_says_our_village_i_39.mp3",
  "The robot smiled. Zero means nobody lives in that house.": "/assets/audio/audio_the_robot_smiled_zero_means_nobody_lives_40.mp3",
  "But the house must still exist, or all the other digits would get confused!": "/assets/audio/audio_but_the_house_must_still_exist_or_all_th_41.mp3",
  "So zero is a placeholder! said Liam. It holds the spot even if it's empty!": "/assets/audio/audio_so_zero_is_a_placeholder_said_liam_it_ho_42.mp3",
  "That's six hundreds, three tens, and four ones!": "/assets/audio/audio_that_s_six_hundreds_three_tens_and_four__44.mp3",
  "Can you make the number exactly right?": "/assets/audio/audio_can_you_make_the_number_exactly_right__49.mp3",
  "Look at the number and blocks. Do they match? Tap True or False!": "/assets/audio/audio_look_at_the_number_and_blocks_do_they_ma_50.mp3",
  "Now fill in the missing digit. What is the value of the highlighted digit?": "/assets/audio/audio_now_fill_in_the_missing_digit_what_is_th_51.mp3",
  "Welcome to the Build the Number station! Use base-ten blocks to build the number shown.": "/assets/audio/audio_welcome_to_the_build_the_number_station__52.mp3",
  "Drag the thousands cubes, hundreds flats, tens rods, and ones units into the right columns!": "/assets/audio/audio_drag_the_thousands_cubes_hundreds_flats__53.mp3",
  "You are now a Place Value Detective! Tap each digit to discover its place and value.": "/assets/audio/audio_you_are_now_a_place_value_detective_tap__54.mp3"
};
