// AUTO-GENERATED — do not edit manually
// Run: node scripts/generate_audio.js
export const audioMap = {
  "Hello Explorer! Today we'll unlock the secret of big numbers!": "/assets/audio/audio_hello_explorer_today_we_ll_unlock_the_se_0.mp3",
  "Get ready to discover thousands, hundreds, tens, and ones!": "/assets/audio/audio_get_ready_to_discover_thousands_hundreds_1.mp3",
  "Welcome to Place Value!": "/assets/audio/audio_welcome_to_place_value__2.mp3",
  "Today, we are going to learn about thousands, hundreds, tens, and ones.": "/assets/audio/audio_today_we_are_going_to_learn_about_thousa_3.mp3",
  "What happens when we put digits into different houses?": "/assets/audio/audio_what_happens_when_we_put_digits_into_dif_4.mp3",
  "Are you ready to explore place value and solve some fun challenges? Let us get started on our learning journey!": "/assets/audio/audio_are_you_ready_to_explore_place_value_and_5.mp3",
  "John just won a video game championship! His score was six thousand, two hundred and forty-eight points. But what does that number actually mean?": "/assets/audio/audio_john_just_won_a_video_game_championship__6.mp3",
  "What do those four digits really tell us? Let's find out!": "/assets/audio/audio_what_do_those_four_digits_really_tell_us_7.mp3",
  "What makes the number 9,999 so special?": "/assets/audio/audio_what_makes_the_number_9_999_so_special__8.mp3",
  "What happens if you add just 1 more to it?": "/assets/audio/audio_what_happens_if_you_add_just_1_more_to_i_9.mp3",
  "How much is a thousand, really?": "/assets/audio/audio_how_much_is_a_thousand_really__10.mp3",
  "If you had 1,000 cookies, how long would it take to eat them all?": "/assets/audio/audio_if_you_had_1_000_cookies_how_long_would__11.mp3",
  "Why do we use commas in big numbers like 1,000?": "/assets/audio/audio_why_do_we_use_commas_in_big_numbers_like_12.mp3",
  "Does the comma change the value of the number?": "/assets/audio/audio_does_the_comma_change_the_value_of_the_n_13.mp3",
  "If a house costs $200,000, what happens to the zeros?": "/assets/audio/audio_if_a_house_costs_200_000_what_happens_to_14.mp3",
  "Do zeros mean 'nothing', or are they super important?": "/assets/audio/audio_do_zeros_mean_nothing_or_are_they_super__15.mp3",
  "Priya, Kai, and Liam were on a school trip to the Number Museum in Singapore. Look! gasped Priya, pointing at a giant glowing display. That number is three thousand, four hundred and seventy-two! It's huge, said Kai. But what does each part mean?": "/assets/audio/audio_priya_kai_and_liam_were_on_a_school_trip_16.mp3",
  "A friendly robot guide rolled up to them. Welcome, explorers! Every digit in a number lives in its own house. Four glowing houses appeared: Thousands, Hundreds, Tens, and Ones. The house a digit lives in tells you its value!": "/assets/audio/audio_a_friendly_robot_guide_rolled_up_to_them_17.mp3",
  "Let's break down three thousand four hundred and seventy-two, said the robot. The digit 3 lives in the Thousands house, so it's worth three thousand! That's like three thousand mangoes from a Mumbai market! laughed Priya. And the 4 in the Hundreds house is worth four hundred!": "/assets/audio/audio_let_s_break_down_three_thousand_four_hun_18.mp3",
  "The 7 in the Tens house is worth seventy, continued the robot. And the 2 in the Ones house is worth just two! So it all adds up! said Kai excitedly. Three thousand plus four hundred plus seventy plus two equals three thousand, four hundred and seventy-two! That's like counting cherry blossoms in Tokyo!": "/assets/audio/audio_the_7_in_the_tens_house_is_worth_seventy_19.mp3",
  "Wait, said Liam. My dad says our village in Nairobi has four thousand and eight people. What about the zeros? The robot smiled. Zero means nobody lives in that house. But the house must still exist, or all the other digits would get confused! So zero is a placeholder! said Liam. It holds the spot even if it's empty!": "/assets/audio/audio_wait_said_liam_my_dad_says_our_village_i_20.mp3",
  "I get it! shouted Kai. The Tokyo Skytree is six hundred and thirty-four metres tall. That's 6 hundreds, 3 tens, and 4 ones! And my school in Mumbai has two thousand, three hundred and fifty students, added Priya. That's 2 thousands, 3 hundreds, 5 tens, and 0 ones! The three friends cheered. They had cracked the code of big numbers!": "/assets/audio/audio_i_get_it_shouted_kai_the_tokyo_skytree_i_21.mp3",
  "Priya, Kai, and Liam were on a school trip to the Number Museum in Singapore.": "/assets/audio/audio_priya_kai_and_liam_were_on_a_school_trip_22.mp3",
  "Look! gasped Priya, pointing at a giant glowing display.": "/assets/audio/audio_look_gasped_priya_pointing_at_a_giant_gl_23.mp3",
  "That number is three thousand, four hundred and seventy-two!": "/assets/audio/audio_that_number_is_three_thousand_four_hundr_24.mp3",
  "It's huge, said Kai. But what does each part mean?": "/assets/audio/audio_it_s_huge_said_kai_but_what_does_each_pa_25.mp3",
  "A friendly robot guide rolled up to them.": "/assets/audio/audio_a_friendly_robot_guide_rolled_up_to_them_26.mp3",
  "Welcome, explorers! Every digit in a number lives in its own house.": "/assets/audio/audio_welcome_explorers_every_digit_in_a_numbe_27.mp3",
  "Four glowing houses appeared: Thousands, Hundreds, Tens, and Ones.": "/assets/audio/audio_four_glowing_houses_appeared_thousands_h_28.mp3",
  "The house a digit lives in tells you its value!": "/assets/audio/audio_the_house_a_digit_lives_in_tells_you_its_29.mp3",
  "Let's break down three thousand, four hundred and seventy-two, said the robot.": "/assets/audio/audio_let_s_break_down_three_thousand_four_hun_30.mp3",
  "The digit three lives in the Thousands house, so it's worth three thousand!": "/assets/audio/audio_the_digit_three_lives_in_the_thousands_h_31.mp3",
  "That's like three thousand mangoes from a Mumbai market! laughed Priya.": "/assets/audio/audio_that_s_like_three_thousand_mangoes_from__32.mp3",
  "And the four in the Hundreds house is worth four hundred!": "/assets/audio/audio_and_the_four_in_the_hundreds_house_is_wo_33.mp3",
  "The seven in the Tens house is worth seventy.": "/assets/audio/audio_the_seven_in_the_tens_house_is_worth_sev_34.mp3",
  "And the two in the Ones house is worth just two!": "/assets/audio/audio_and_the_two_in_the_ones_house_is_worth_j_35.mp3",
  "So it all adds up! said Kai excitedly.": "/assets/audio/audio_so_it_all_adds_up_said_kai_excitedly__36.mp3",
  "Three thousand plus four hundred plus seventy plus two equals three thousand, four hundred and seventy-two!": "/assets/audio/audio_three_thousand_plus_four_hundred_plus_se_37.mp3",
  "That's like counting cherry blossoms in Tokyo!": "/assets/audio/audio_that_s_like_counting_cherry_blossoms_in__38.mp3",
  "Wait, said Liam. My dad says our village in Nairobi has four thousand and eight people. What about the zeros?": "/assets/audio/audio_wait_said_liam_my_dad_says_our_village_i_39.mp3",
  "The robot smiled. Zero means nobody lives in that house.": "/assets/audio/audio_the_robot_smiled_zero_means_nobody_lives_40.mp3",
  "But the house must still exist, or all the other digits would get confused!": "/assets/audio/audio_but_the_house_must_still_exist_or_all_th_41.mp3",
  "So zero is a placeholder! said Liam. It holds the spot even if it's empty!": "/assets/audio/audio_so_zero_is_a_placeholder_said_liam_it_ho_42.mp3",
  "I get it! shouted Kai. The Tokyo Skytree is six hundred and thirty-four metres tall.": "/assets/audio/audio_i_get_it_shouted_kai_the_tokyo_skytree_i_43.mp3",
  "That's six hundreds, three tens, and four ones!": "/assets/audio/audio_that_s_six_hundreds_three_tens_and_four__44.mp3",
  "And my school in Mumbai has two thousand, three hundred and fifty students, added Priya.": "/assets/audio/audio_and_my_school_in_mumbai_has_two_thousand_45.mp3",
  "That's two thousands, three hundreds, five tens, and zero ones!": "/assets/audio/audio_that_s_two_thousands_three_hundreds_five_46.mp3",
  "The three friends cheered. They had cracked the code of big numbers!": "/assets/audio/audio_the_three_friends_cheered_they_had_crack_47.mp3",
  "Build the number using the Place Value blocks!": "/assets/audio/audio_build_the_number_using_the_place_value_b_48.mp3",
  "Can you make the number exactly right?": "/assets/audio/audio_can_you_make_the_number_exactly_right__49.mp3",
  "Look at the number and blocks. Do they match? Tap True or False!": "/assets/audio/audio_look_at_the_number_and_blocks_do_they_ma_50.mp3",
  "Now fill in the missing digit. What is the value of the highlighted digit?": "/assets/audio/audio_now_fill_in_the_missing_digit_what_is_th_51.mp3",
  "Welcome to the Build the Number station! Use base-ten blocks to build the number shown.": "/assets/audio/audio_welcome_to_the_build_the_number_station__52.mp3",
  "Drag the thousands cubes, hundreds flats, tens rods, and ones units into the right columns!": "/assets/audio/audio_drag_the_thousands_cubes_hundreds_flats__53.mp3",
  "You are now a Place Value Detective! Tap each digit to discover its place and value.": "/assets/audio/audio_you_are_now_a_place_value_detective_tap__54.mp3",
  "Remember: the same digit can have completely different values depending on its position!": "/assets/audio/audio_remember_the_same_digit_can_have_complet_55.mp3",
  "Time to Expand It! Drag the value cards to build the expanded form of the number.": "/assets/audio/audio_time_to_expand_it_drag_the_value_cards_t_56.mp3",
  "Amazing! You built it perfectly!": "/assets/audio/audio_amazing_you_built_it_perfectly__57.mp3",
  "That's not quite right. Let's try again!": "/assets/audio/audio_that_s_not_quite_right_let_s_try_again__58.mp3",
  "Excellent! That is the correct value!": "/assets/audio/audio_excellent_that_is_the_correct_value__59.mp3",
  "Almost there! Remember to check the place carefully.": "/assets/audio/audio_almost_there_remember_to_check_the_place_60.mp3",
  "Great job completing all three stations! Now let's play and practice what you've learned!": "/assets/audio/audio_great_job_completing_all_three_stations__61.mp3",
  "Great job!": "/assets/audio/audio_great_job__62.mp3",
  "You got it right!": "/assets/audio/audio_you_got_it_right__63.mp3",
  "Yes! You found it!": "/assets/audio/audio_yes_you_found_it__64.mp3",
  "Great job completing the Detective station!": "/assets/audio/audio_great_job_completing_the_detective_stati_65.mp3",
  "Correct!": "/assets/audio/audio_correct__66.mp3",
  "Welcome to Planet Ones!": "/assets/audio/audio_welcome_to_planet_ones__67.mp3",
  "Welcome to Hundreds Haven!": "/assets/audio/audio_welcome_to_hundreds_haven__68.mp3",
  "Welcome to Thousand Tower!": "/assets/audio/audio_welcome_to_thousand_tower__69.mp3",
  "Welcome to Value Village!": "/assets/audio/audio_welcome_to_value_village__70.mp3",
  "Welcome to Expanded Explorer!": "/assets/audio/audio_welcome_to_expanded_explorer__71.mp3",
  "Welcome to Zero Zone!": "/assets/audio/audio_welcome_to_zero_zone__72.mp3",
  "Welcome to Double Zero Desert!": "/assets/audio/audio_welcome_to_double_zero_desert__73.mp3",
  "Welcome to Word Wizard!": "/assets/audio/audio_welcome_to_word_wizard__74.mp3",
  "Welcome to Mixed Challenge Mesa!": "/assets/audio/audio_welcome_to_mixed_challenge_mesa__75.mp3",
  "Welcome to Master Mountain!": "/assets/audio/audio_welcome_to_master_mountain__76.mp3",
  "Planet Ones Complete!": "/assets/audio/audio_planet_ones_complete__77.mp3",
  "Hundreds Haven Complete!": "/assets/audio/audio_hundreds_haven_complete__78.mp3",
  "Thousand Tower Complete!": "/assets/audio/audio_thousand_tower_complete__79.mp3",
  "Value Village Complete!": "/assets/audio/audio_value_village_complete__80.mp3",
  "Expanded Explorer Complete!": "/assets/audio/audio_expanded_explorer_complete__81.mp3",
  "Zero Zone Complete!": "/assets/audio/audio_zero_zone_complete__82.mp3",
  "Double Zero Desert Complete!": "/assets/audio/audio_double_zero_desert_complete__83.mp3",
  "Word Wizard Complete!": "/assets/audio/audio_word_wizard_complete__84.mp3",
  "Mixed Challenge Mesa Complete!": "/assets/audio/audio_mixed_challenge_mesa_complete__85.mp3",
  "Master Mountain Complete!": "/assets/audio/audio_master_mountain_complete__86.mp3",
  "Wonderful work today, Explorer! You have mastered place value!": "/assets/audio/audio_wonderful_work_today_explorer_you_have_m_87.mp3",
  "Wonderful work today, Explorer! You have mastered place value! Let's look at your achievements.": "/assets/audio/audio_wonderful_work_today_explorer_you_have_m_88.mp3",
  "Pick your favourite big number and tell me how many thousands, hundreds, tens, and ones it has.": "/assets/audio/audio_pick_your_favourite_big_number_and_tell__89.mp3",
  "What did you learn about Place Value?": "/assets/audio/audio_what_did_you_learn_about_place_value__90.mp3",
  "How confident do you feel about 4-digit numbers?": "/assets/audio/audio_how_confident_do_you_feel_about_4_digit__91.mp3"
};
